os: osx
language: objective-c
osx_image: xcode9.4    

branches:
  only:
    - master

jobs:
  include:
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core   
      script: travis_wait 30 bats Amphorae/A/*
      name: "A Amphorae - Carthage Stable"
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core  
      script: travis_wait 30 bats Amphorae/C/*
      name: "C Amphorae - Carthage Stable"
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core  
      script: travis_wait 30 bats Amphorae/F/*
      name: "F Amphorae - Carthage Stable"
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core    
      script: travis_wait 30 bats Amphorae/M/*
      name: "M Amphorae - Carthage Stable"
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core    
      script: travis_wait 30 bats Amphorae/S/*
      name: "S Amphorae - Carthage Stable"
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core
      script: travis_wait 30 bats Amphorae/R/*
      name: "R Amphorae - Carthage Stable"
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core 
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/A/*
      name: "A Amphorae - Carthage HEAD"
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/C/*
      name: "C Amphorae - Carthage HEAD"
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core
        - brew uninstall carthage
        - brew install carthage --HEAD 
      script: travis_wait 30 bats Amphorae/F/*
      name: "F Amphorae - Carthage HEAD"
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/M/*
      name: "M Amphorae - Carthage HEAD"
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core 
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/S/*
      name: "S Amphorae - Carthage HEAD"
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core 
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/R/*
      name: "R Amphorae - Carthage HEAD"

