os: osx
language: objective-c
osx_image: xcode9.4    

branches:
  only:
    - master

jobs:
  include:
  # Carthage Stable
    # A
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core   
      script: travis_wait 30 bats Amphorae/A/*
      name: "A Amphorae - Carthage Stable"
    # C
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core  
      script: travis_wait 30 bats Amphorae/C/*
      name: "C Amphorae - Carthage Stable"
    # F
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core  
      script: travis_wait 30 bats Amphorae/F/*
      name: "F Amphorae - Carthage Stable"
    # H
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core  
      script: travis_wait 30 bats Amphorae/H/*
      name: "H Amphorae - Carthage Stable"
    # K
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core  
      script: travis_wait 30 bats Amphorae/K/*
      name: "K Amphorae - Carthage Stable"  
    # L
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core   
      script: travis_wait 30 bats Amphorae/L/*
      name: "L Amphorae - Carthage Stable"
    # M
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core    
      script: travis_wait 30 bats Amphorae/M/*
      name: "M Amphorae - Carthage Stable"
    # S
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core    
      script: travis_wait 30 bats Amphorae/S/*
      name: "S Amphorae - Carthage Stable"
    # R
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core
      script: travis_wait 30 bats Amphorae/R/*
      name: "R Amphorae - Carthage Stable"
  # Carthage Stable
    # A
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core 
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/A/*
      name: "A Amphorae - Carthage HEAD"
    # C
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/C/*
      name: "C Amphorae - Carthage HEAD"
    # F
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core
        - brew uninstall carthage
        - brew install carthage --HEAD 
      script: travis_wait 30 bats Amphorae/F/*
      name: "F Amphorae - Carthage HEAD"
    # H
    - stage: "Tests" 
      install:
        - brew update
        - brew install bats-core
        - brew uninstall carthage
        - brew install carthage --HEAD 
      script: travis_wait 30 bats Amphorae/H/*
      name: "H Amphorae - Carthage HEAD"
    # K
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/K/*
      name: "K Amphorae - Carthage HEAD"
    # L
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/L/*
      name: "L Amphorae - Carthage HEAD"
    # M
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/M/*
      name: "M Amphorae - Carthage HEAD"
    # S
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core 
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/S/*
      name: "S Amphorae - Carthage HEAD"
    # R
    - stage: "Tests"
      install:
        - brew update
        - brew install bats-core 
        - brew uninstall carthage
        - brew install carthage --HEAD
      script: travis_wait 30 bats Amphorae/R/*
      name: "R Amphorae - Carthage HEAD"

