os: osx
language: objective-c
osx_image: xcode9.4

branches:
  only:
    - master

install:
  - brew update
  - brew install bats-core

jobs:
  include:
    - stage: test
      script:
        - bats Amphorae/A/* 
      script:
        - bats Amphorae/S/*

